databaseChangeLog:
  - changeSet:
      id: tag
      author: snikitin
      changes:
        - tagDatabase:
            tag: 020-add-unique-index-field-for-switch-connected-devices

  - changeSet:
      id: add_unique_index_field_for_switch_connected_devices
      author: snikitin
      changes:
        - sql: "CREATE PROPERTY switch_connected_device.unique_index IF NOT EXISTS STRING"
      rollback:
        - sql: "DROP PROPERTY switch_connected_device.unique_index IF EXISTS"
